# flask를 도커 컨테이너로 실행하지 않는 코드. flask는 따로 켜주어야 함!! 
# flask 개발 시 테스트하는 용도 
# spring(eureka, gateway, auth)가 컨테이너로 실행됩니다. 
# localhost:8088로 요청을 보내면 처리됩니다. 

version: '3'
services:
  discovery:
    build: 
      context: ./discovery
    ports: 
      - "8761:8761"

  gateway:
    build: 
      context: ./gateway
    depends_on:
      - discovery
    ports: 
      - "8088:8088"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - flask.url=http://host.docker.internal:5000

  auth:
    build: 
      context: ./auth
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - flask.url=http://host.docker.internal:5000
    depends_on:
      - gateway
      - discovery
    ports: 
      - "8081:8081" 

# 실행: docker-compose -f docker-compose-without-flask.yml up --build