server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

flask:
  url: http://localhost:5000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ['http://localhost:3000', 'http://host.docker.internal:3000']
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: flask
          uri: ${flask.url}
          predicates:
            - Path=/flask/**
          filters:
            - AuthorizationHeaderFilter

