version: "3"
services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3030:80
  

# docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d --build로 진행